-- ============================================================
-- KOMS — Database Schema
-- Generated by scaffold-schema on 2026-07-12
-- Source: PRD.md confirmed 2026-07-12
-- Every table traces to a screen in PRD.md's Screen Inventory.
-- ============================================================

-- ============================================================
-- ROOT ENTITY
-- ============================================================
-- Multi-tenant root. 1 row seeded for v1 (Gio's center, Indonesia).
-- Exists now so Singapore/other-country expansion never requires a schema rebuild.
create table centers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  country text not null default 'Indonesia', -- 'Indonesia' | 'Singapore' | others as Kodecoon expands
  created_at timestamptz default now()
);

-- ============================================================
-- BUILD NOW — MVP (all P0, per the locked PRD)
-- ============================================================

-- Staff (teacher/center_manager/admin) AND parent accounts share this table.
-- id = auth.uid(), mirrors Supabase auth.users. Role-based, RLS-ready from day one
-- (same pattern as TCS Coffee's customer/admin/POS roles).
create table users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null default 'teacher', -- 'teacher' | 'center_manager' | 'admin' | 'parent'
  center_id uuid references centers(id), -- null for parents, required for staff
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  -- Enforced, not just documented: several RLS policies scope by
  -- "center_id in (select center_id from users where id = auth.uid())".
  -- A parent with a non-null center_id would silently widen those policies to
  -- every student in the center, so the invariant has to be a constraint.
  constraint users_parent_has_no_center
    check (role <> 'parent' or center_id is null)
);

create table classes (
  id uuid primary key default gen_random_uuid(),
  center_id uuid not null references centers(id),
  teacher_id uuid not null references users(id),
  name text not null,           -- e.g. 'Scratch Junior', 'RCB', 'RGD Lv 2'
  age_bracket text,             -- e.g. '5-8', '8-12', '13-19'
  -- total lesson count is derived from COUNT(lessons) where class_id = this class,
  -- not stored here — avoids two sources of truth for curriculum size
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table students (
  id uuid primary key default gen_random_uuid(),
  center_id uuid not null references centers(id),
  name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table enrollments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  class_id uuid not null references classes(id) on delete cascade,
  enrolled_date date not null default current_date,
  created_at timestamptz default now(),
  unique (student_id, class_id)
);

create table sessions (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references classes(id),
  teacher_id uuid not null references users(id),
  session_date date not null,
  session_time time,            -- nullable; used by My Schedule
  status text not null default 'scheduled', -- 'scheduled' | 'completed'
  notes text,                   -- Gio's rough session notes; feeds the AI report draft
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table attendance (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  student_id uuid not null references students(id) on delete cascade,
  status text not null default 'unmarked', -- 'present' | 'absent' | 'unmarked'
  created_at timestamptz default now(),
  unique (session_id, student_id)
);

create table session_videos (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  drive_file_id text not null,
  drive_link text not null,     -- shareable preview link — never raw video bytes in the DB
  created_at timestamptz default now()
);

-- The lesson plan (curriculum template) for a class — e.g. 24 ordered lessons
-- for RCB. Admin-authored. This is what powers the snake-path journey view:
-- each row is one node on the path.
create table lessons (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references classes(id) on delete cascade,
  sequence_number int not null, -- position on the journey path, 1-indexed
  title text not null,
  description text,
  created_at timestamptz default now(),
  unique (class_id, sequence_number)
);

-- Per-student completion state for each lesson node. This replaces the old
-- flat "credits" ledger — a completed lesson IS the credit, now named and
-- ordered instead of an anonymous count.
create table student_lesson_progress (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  lesson_id uuid not null references lessons(id) on delete cascade,
  status text not null default 'locked', -- 'locked' | 'unlocked' | 'completed'
  session_id uuid references sessions(id), -- which session completed it, if any
  completed_date date,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (student_id, lesson_id)
);

create table report_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  design_reference text,        -- reference to the Claude Design template asset
  is_default boolean not null default true,
  created_at timestamptz default now()
);

create table reports (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  class_id uuid references classes(id),
  template_id uuid references report_templates(id),
  raw_notes text,                -- Gio's rough notes — input to the AI draft
  ai_draft_text text,            -- Claude API output, editable before export
  final_text text,               -- text actually exported to PDF
  final_pdf_url text,
  generated_date date not null default current_date,
  created_at timestamptz default now()
);

create table student_guardians (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  guardian_id uuid not null references users(id) on delete cascade, -- users.role = 'parent'
  created_at timestamptz default now(),
  unique (student_id, guardian_id)
);

-- ============================================================
-- ARCHITECT NOW, BUILD LATER — Future phases
-- ============================================================
-- Deliberately empty. Every V2 item (academy-wide scheduling, Center Manager/Admin
-- screens, multi-center rollout, multiple report templates) reuses tables already
-- defined above via role/center_id — no speculative tables needed for v1.
-- Payments/CRM are permanently out of KOMS's remit (stay on OClass) — not modeled at all.

-- ============================================================
-- ROW LEVEL SECURITY
-- Non-negotiable: this data includes minors. A parent must never be able to
-- retrieve another family's student data under any query.
-- ============================================================

alter table centers enable row level security;
alter table users enable row level security;
alter table classes enable row level security;
alter table students enable row level security;
alter table enrollments enable row level security;
alter table sessions enable row level security;
alter table attendance enable row level security;
alter table session_videos enable row level security;
alter table report_templates enable row level security;
alter table reports enable row level security;
alter table student_guardians enable row level security;

-- ------------------------------------------------------------
-- CURRENT-USER HELPERS
-- ------------------------------------------------------------
-- A policy ON users may not read FROM users. While rewriting a query the
-- planner expands the policy, hits the subquery's reference to users, and
-- re-applies the same policy to it — Postgres detects the loop and aborts the
-- whole statement with 42P17 "infinite recursion detected in policy for
-- relation users". It is not a slow query or a subtle wrong answer: every
-- statement touching users fails, including proxy.ts's role lookup, which runs
-- on every authenticated request. The failure also propagates outward, because
-- policies on other tables (students_all_teacher and friends) read from users,
-- so expanding *those* re-enters users' policies and trips the same check.
--
-- security definer breaks the loop: the body runs as the function owner
-- (postgres, when this file is run from the SQL editor), and the owner is not
-- subject to RLS, so no policy is expanded inside it. plpgsql rather than sql
-- is deliberate — the planner inlines trivial sql functions, and an inlined
-- body would be back inside the caller's query tree with RLS applied again.
-- (`set search_path` already blocks inlining on its own; the language choice
-- keeps that from being load-bearing.) Both functions are scoped to
-- auth.uid(), so they expose nothing the caller can't already read from its
-- own row via users_select_own.
create or replace function public.current_user_role()
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  r text;
begin
  select role into r from public.users where id = auth.uid();
  return r;
end;
$$;

create or replace function public.current_user_center()
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  c uuid;
begin
  select center_id into c from public.users where id = auth.uid();
  return c;
end;
$$;

revoke execute on function public.current_user_role() from public;
revoke execute on function public.current_user_center() from public;
-- anon is granted too, deliberately. Policies are evaluated for whoever runs
-- the query, so a logged-out request touching report_templates would fail with
-- "permission denied for function" instead of the empty result the app expects.
-- Both functions key on auth.uid(), which is null for anon, so they return null
-- and every policy using them is simply false.
grant execute on function public.current_user_role() to authenticated, anon;
grant execute on function public.current_user_center() to authenticated, anon;

-- users: everyone sees/updates only their own row
create policy "users_select_own" on users for select using (id = auth.uid());

-- WITH CHECK is spelled out deliberately. Postgres reuses the USING expression
-- as WITH CHECK when it is omitted, and "id = auth.uid()" still holds after a
-- row rewrites its OWN role — so the omitted form let any authenticated parent
-- run `update users set role='admin', center_id=<their child's class center>`
-- and inherit every *_admin_manage_center policy below. The anon key is public
-- by design, so that reaches PostgREST directly and never passes a route guard.
-- Column-level immutability is enforced by the trigger underneath; this clause
-- keeps the row-level intent readable at the policy site.
create policy "users_update_own" on users for update
  using (id = auth.uid())
  with check (id = auth.uid());

-- Role and center assignment are not self-service. Blocks only self-edits, so
-- an admin managing OTHER staff via users_admin_manage_center is unaffected,
-- as are service-role operations (auth.uid() is null there).
create or replace function prevent_self_privilege_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() = new.id
     and (new.role is distinct from old.role
          or new.center_id is distinct from old.center_id) then
    raise exception 'role and center_id cannot be changed by the account holder';
  end if;
  return new;
end;
$$;

-- create trigger has no "or replace"; the drop keeps a re-run of this file from
-- failing halfway, which matters while Step 7 is still being iterated on.
drop trigger if exists users_block_self_escalation on users;
create trigger users_block_self_escalation
  before update on users
  for each row execute function prevent_self_privilege_escalation();

-- centers: staff can see their own center
create policy "centers_select_staff" on centers for select using (
  id in (select center_id from users where id = auth.uid())
);

-- classes: teacher owns their classes; parent sees classes their child is enrolled in
-- WITH CHECK also pins center_id: with the inherited form a teacher could move
-- one of their own classes into another center, where that center's admin
-- policies would pick it up. Harmless in single-center v1, wrong the moment a
-- second center exists.
create policy "classes_all_teacher" on classes for all
  using (teacher_id = auth.uid())
  with check (
    teacher_id = auth.uid()
    and center_id in (select center_id from users where id = auth.uid())
  );
create policy "classes_select_parent" on classes for select using (
  id in (
    select e.class_id from enrollments e
    join student_guardians sg on sg.student_id = e.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- students: teacher manages students in their center; parent sees only their linked child
create policy "students_all_teacher" on students for all using (
  center_id in (select center_id from users where id = auth.uid() and role in ('teacher','center_manager','admin'))
);
create policy "students_select_parent" on students for select using (
  id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- enrollments: teacher manages enrollments for their own classes; parent sees their child's
create policy "enrollments_all_teacher" on enrollments for all using (
  class_id in (select id from classes where teacher_id = auth.uid())
);
create policy "enrollments_select_parent" on enrollments for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- sessions: teacher manages their own sessions; parent sees sessions for their child's classes
create policy "sessions_all_teacher" on sessions for all using (teacher_id = auth.uid());
create policy "sessions_select_parent" on sessions for select using (
  class_id in (
    select e.class_id from enrollments e
    join student_guardians sg on sg.student_id = e.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- attendance: teacher manages for their sessions; parent sees only their own child's rows
-- Both halves are required. Gating on session_id alone lets a teacher who owns
-- the session write an attendance row for ANY student in the academy; the
-- enrollment clause pins student_id to the session's own class.
create policy "attendance_all_teacher" on attendance for all using (
  session_id in (select id from sessions where teacher_id = auth.uid())
  and student_id in (
    select e.student_id from enrollments e
    join sessions s on s.class_id = e.class_id
    where s.id = attendance.session_id
  )
);
create policy "attendance_select_parent" on attendance for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- session_videos: teacher manages for their sessions; parent sees videos tied to their child's sessions
create policy "session_videos_all_teacher" on session_videos for all using (
  session_id in (select id from sessions where teacher_id = auth.uid())
);
create policy "session_videos_select_parent" on session_videos for select using (
  session_id in (
    select a.session_id from attendance a
    join student_guardians sg on sg.student_id = a.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- lessons: teacher/admin manage lessons for their own classes; parent/student can view
-- the lesson plan for classes their child is enrolled in (needed to render the journey)
alter table lessons enable row level security;
alter table student_lesson_progress enable row level security;

create policy "lessons_all_teacher" on lessons for all using (
  class_id in (select id from classes where teacher_id = auth.uid())
);
create policy "lessons_select_parent" on lessons for select using (
  class_id in (
    select e.class_id from enrollments e
    join student_guardians sg on sg.student_id = e.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- student_lesson_progress: teacher manages for their students; parent sees only their own child's progress
-- As with attendance: the lesson clause alone would let a teacher mark any
-- student in the academy complete on one of their own lessons. The enrollment
-- clause pins student_id to a class that actually contains that lesson.
create policy "progress_all_teacher" on student_lesson_progress for all using (
  lesson_id in (
    select l.id from lessons l
    join classes c on c.id = l.class_id
    where c.teacher_id = auth.uid()
  )
  and student_id in (
    select e.student_id from enrollments e
    join lessons l on l.class_id = e.class_id
    where l.id = student_lesson_progress.lesson_id
  )
);
create policy "progress_select_parent" on student_lesson_progress for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- reports: teacher manages for their students; parent sees only their own child's reports
create policy "reports_all_teacher" on reports for all using (
  student_id in (
    select e.student_id from enrollments e
    join classes c on c.id = e.class_id
    where c.teacher_id = auth.uid()
  )
);
create policy "reports_select_parent" on reports for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- report_templates: any authenticated staff can read; Gio edits the row directly via
-- the Supabase dashboard in v1 — no in-app editor, per PRD Out of Scope.
-- "auth.uid() is not null" was every authenticated user, parents included —
-- the name said staff and the expression said anyone. Nothing in the parent
-- portal reads this table (only the two staff report pages do), so the narrow
-- form is what the app actually needs.
create policy "report_templates_select_staff" on report_templates for select using (
  (select public.current_user_role()) in ('teacher','center_manager','admin')
);

-- student_guardians: teacher creates links when adding a student's parent; parent sees only their own links
-- The role filter matches students_all_teacher above and is load-bearing: without
-- it, any user row whose center_id happens to be set — including a parent's —
-- would get ALL (insert/update/delete) on guardian links, letting them attach
-- themselves to another family's child and inherit every parent policy that
-- traverses student_guardians. The users_parent_has_no_center constraint closes
-- the same hole from the other side; both stay.
create policy "student_guardians_all_teacher" on student_guardians for all using (
  student_id in (
    select id from students where center_id in (
      select center_id from users
      where id = auth.uid() and role in ('teacher','center_manager','admin')
    )
  )
);
create policy "student_guardians_select_own" on student_guardians for select using (guardian_id = auth.uid());

-- ============================================================
-- ADMIN OVERRIDE POLICIES
-- role = 'admin' gets full access across the whole center — not just their
-- own classes/sessions. This is what powers Manage Teachers and Academy
-- Schedule. Scoped to center_id, not global, so it stays multi-tenant-safe
-- as more centers come online later.
-- ============================================================

-- Reads the caller's own role/center through the security definer helpers
-- rather than a subquery on users — see the CURRENT-USER HELPERS note above.
-- Each call is wrapped in (select ...) so the planner evaluates it once as an
-- InitPlan instead of once per candidate row.
-- WITH CHECK is spelled out for the same reason it is on users_update_own: the
-- inherited form would be identical here, but an admin editing staff is
-- exactly the path where an accidental widening would be worst.
-- center_manager is deliberately absent from the managed set, matching the
-- pre-existing policy — v1 has no such account, and adding one to the list is
-- a privilege decision, not a bug fix.
create policy "users_admin_manage_center" on users for all
  using (
    (select public.current_user_role()) = 'admin'
    and role in ('teacher','admin')
    and center_id = (select public.current_user_center())
  )
  with check (
    (select public.current_user_role()) = 'admin'
    and role in ('teacher','admin')
    and center_id = (select public.current_user_center())
  );

create policy "classes_admin_manage_center" on classes for all using (
  center_id in (select center_id from users where id = auth.uid() and role = 'admin')
);

create policy "sessions_admin_manage_center" on sessions for all using (
  class_id in (
    select id from classes where center_id in (
      select center_id from users where id = auth.uid() and role = 'admin'
    )
  )
);

create policy "lessons_admin_manage_center" on lessons for all using (
  class_id in (
    select id from classes where center_id in (
      select center_id from users where id = auth.uid() and role = 'admin'
    )
  )
);
