-- ============================================================
-- KOMS — Database Schema
-- Generated by scaffold-schema on 2026-07-12
-- Source: PRD.md confirmed 2026-07-12
-- Every table traces to a screen in PRD.md's Screen Inventory.
-- ============================================================

-- ============================================================
-- ROOT ENTITY
-- ============================================================
-- Multi-tenant root. 1 row seeded for v1 (Gio's center, Indonesia).
-- Exists now so Singapore/other-country expansion never requires a schema rebuild.
create table centers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  country text not null default 'Indonesia', -- 'Indonesia' | 'Singapore' | others as Kodecoon expands
  created_at timestamptz default now()
);

-- ============================================================
-- BUILD NOW — MVP (all P0, per the locked PRD)
-- ============================================================

-- Staff (teacher/center_manager/admin) AND parent accounts share this table.
-- id = auth.uid(), mirrors Supabase auth.users. Role-based, RLS-ready from day one
-- (same pattern as TCS Coffee's customer/admin/POS roles).
create table users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null default 'teacher', -- 'teacher' | 'center_manager' | 'admin' | 'parent'
  center_id uuid references centers(id), -- null for parents, required for staff
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table classes (
  id uuid primary key default gen_random_uuid(),
  center_id uuid not null references centers(id),
  teacher_id uuid not null references users(id),
  name text not null,           -- e.g. 'Scratch Junior', 'RCB', 'RGD Lv 2'
  age_bracket text,             -- e.g. '5-8', '8-12', '13-19'
  -- total lesson count is derived from COUNT(lessons) where class_id = this class,
  -- not stored here — avoids two sources of truth for curriculum size
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table students (
  id uuid primary key default gen_random_uuid(),
  center_id uuid not null references centers(id),
  name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table enrollments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  class_id uuid not null references classes(id) on delete cascade,
  enrolled_date date not null default current_date,
  created_at timestamptz default now(),
  unique (student_id, class_id)
);

create table sessions (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references classes(id),
  teacher_id uuid not null references users(id),
  session_date date not null,
  session_time time,            -- nullable; used by My Schedule
  status text not null default 'scheduled', -- 'scheduled' | 'completed'
  notes text,                   -- Gio's rough session notes; feeds the AI report draft
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table attendance (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  student_id uuid not null references students(id) on delete cascade,
  status text not null default 'unmarked', -- 'present' | 'absent' | 'unmarked'
  created_at timestamptz default now(),
  unique (session_id, student_id)
);

create table session_videos (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  drive_file_id text not null,
  drive_link text not null,     -- shareable preview link — never raw video bytes in the DB
  created_at timestamptz default now()
);

-- The lesson plan (curriculum template) for a class — e.g. 24 ordered lessons
-- for RCB. Admin-authored. This is what powers the snake-path journey view:
-- each row is one node on the path.
create table lessons (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references classes(id) on delete cascade,
  sequence_number int not null, -- position on the journey path, 1-indexed
  title text not null,
  description text,
  created_at timestamptz default now(),
  unique (class_id, sequence_number)
);

-- Per-student completion state for each lesson node. This replaces the old
-- flat "credits" ledger — a completed lesson IS the credit, now named and
-- ordered instead of an anonymous count.
create table student_lesson_progress (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  lesson_id uuid not null references lessons(id) on delete cascade,
  status text not null default 'locked', -- 'locked' | 'unlocked' | 'completed'
  session_id uuid references sessions(id), -- which session completed it, if any
  completed_date date,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (student_id, lesson_id)
);

create table report_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  design_reference text,        -- reference to the Claude Design template asset
  is_default boolean not null default true,
  created_at timestamptz default now()
);

create table reports (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  class_id uuid references classes(id),
  template_id uuid references report_templates(id),
  raw_notes text,                -- Gio's rough notes — input to the AI draft
  ai_draft_text text,            -- Claude API output, editable before export
  final_text text,               -- text actually exported to PDF
  final_pdf_url text,
  generated_date date not null default current_date,
  created_at timestamptz default now()
);

create table student_guardians (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references students(id) on delete cascade,
  guardian_id uuid not null references users(id) on delete cascade, -- users.role = 'parent'
  created_at timestamptz default now(),
  unique (student_id, guardian_id)
);

-- ============================================================
-- ARCHITECT NOW, BUILD LATER — Future phases
-- ============================================================
-- Deliberately empty. Every V2 item (academy-wide scheduling, Center Manager/Admin
-- screens, multi-center rollout, multiple report templates) reuses tables already
-- defined above via role/center_id — no speculative tables needed for v1.
-- Payments/CRM are permanently out of KOMS's remit (stay on OClass) — not modeled at all.

-- ============================================================
-- ROW LEVEL SECURITY
-- Non-negotiable: this data includes minors. A parent must never be able to
-- retrieve another family's student data under any query.
-- ============================================================

alter table centers enable row level security;
alter table users enable row level security;
alter table classes enable row level security;
alter table students enable row level security;
alter table enrollments enable row level security;
alter table sessions enable row level security;
alter table attendance enable row level security;
alter table session_videos enable row level security;
alter table report_templates enable row level security;
alter table reports enable row level security;
alter table student_guardians enable row level security;

-- users: everyone sees/updates only their own row
create policy "users_select_own" on users for select using (id = auth.uid());
create policy "users_update_own" on users for update using (id = auth.uid());

-- centers: staff can see their own center
create policy "centers_select_staff" on centers for select using (
  id in (select center_id from users where id = auth.uid())
);

-- classes: teacher owns their classes; parent sees classes their child is enrolled in
create policy "classes_all_teacher" on classes for all using (teacher_id = auth.uid());
create policy "classes_select_parent" on classes for select using (
  id in (
    select e.class_id from enrollments e
    join student_guardians sg on sg.student_id = e.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- students: teacher manages students in their center; parent sees only their linked child
create policy "students_all_teacher" on students for all using (
  center_id in (select center_id from users where id = auth.uid() and role in ('teacher','center_manager','admin'))
);
create policy "students_select_parent" on students for select using (
  id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- enrollments: teacher manages enrollments for their own classes; parent sees their child's
create policy "enrollments_all_teacher" on enrollments for all using (
  class_id in (select id from classes where teacher_id = auth.uid())
);
create policy "enrollments_select_parent" on enrollments for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- sessions: teacher manages their own sessions; parent sees sessions for their child's classes
create policy "sessions_all_teacher" on sessions for all using (teacher_id = auth.uid());
create policy "sessions_select_parent" on sessions for select using (
  class_id in (
    select e.class_id from enrollments e
    join student_guardians sg on sg.student_id = e.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- attendance: teacher manages for their sessions; parent sees only their own child's rows
create policy "attendance_all_teacher" on attendance for all using (
  session_id in (select id from sessions where teacher_id = auth.uid())
);
create policy "attendance_select_parent" on attendance for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- session_videos: teacher manages for their sessions; parent sees videos tied to their child's sessions
create policy "session_videos_all_teacher" on session_videos for all using (
  session_id in (select id from sessions where teacher_id = auth.uid())
);
create policy "session_videos_select_parent" on session_videos for select using (
  session_id in (
    select a.session_id from attendance a
    join student_guardians sg on sg.student_id = a.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- lessons: teacher/admin manage lessons for their own classes; parent/student can view
-- the lesson plan for classes their child is enrolled in (needed to render the journey)
alter table lessons enable row level security;
alter table student_lesson_progress enable row level security;

create policy "lessons_all_teacher" on lessons for all using (
  class_id in (select id from classes where teacher_id = auth.uid())
);
create policy "lessons_select_parent" on lessons for select using (
  class_id in (
    select e.class_id from enrollments e
    join student_guardians sg on sg.student_id = e.student_id
    where sg.guardian_id = auth.uid()
  )
);

-- student_lesson_progress: teacher manages for their students; parent sees only their own child's progress
create policy "progress_all_teacher" on student_lesson_progress for all using (
  lesson_id in (
    select l.id from lessons l
    join classes c on c.id = l.class_id
    where c.teacher_id = auth.uid()
  )
);
create policy "progress_select_parent" on student_lesson_progress for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- reports: teacher manages for their students; parent sees only their own child's reports
create policy "reports_all_teacher" on reports for all using (
  student_id in (
    select e.student_id from enrollments e
    join classes c on c.id = e.class_id
    where c.teacher_id = auth.uid()
  )
);
create policy "reports_select_parent" on reports for select using (
  student_id in (select student_id from student_guardians where guardian_id = auth.uid())
);

-- report_templates: any authenticated staff can read; Gio edits the row directly via
-- the Supabase dashboard in v1 — no in-app editor, per PRD Out of Scope.
create policy "report_templates_select_staff" on report_templates for select using (auth.uid() is not null);

-- student_guardians: teacher creates links when adding a student's parent; parent sees only their own links
create policy "student_guardians_all_teacher" on student_guardians for all using (
  student_id in (select id from students where center_id in (select center_id from users where id = auth.uid()))
);
create policy "student_guardians_select_own" on student_guardians for select using (guardian_id = auth.uid());

-- ============================================================
-- ADMIN OVERRIDE POLICIES
-- role = 'admin' gets full access across the whole center — not just their
-- own classes/sessions. This is what powers Manage Teachers and Academy
-- Schedule. Scoped to center_id, not global, so it stays multi-tenant-safe
-- as more centers come online later.
-- ============================================================

create policy "users_admin_manage_center" on users for all using (
  role in ('teacher','admin') and center_id in (
    select center_id from users where id = auth.uid() and role = 'admin'
  )
);

create policy "classes_admin_manage_center" on classes for all using (
  center_id in (select center_id from users where id = auth.uid() and role = 'admin')
);

create policy "sessions_admin_manage_center" on sessions for all using (
  class_id in (
    select id from classes where center_id in (
      select center_id from users where id = auth.uid() and role = 'admin'
    )
  )
);

create policy "lessons_admin_manage_center" on lessons for all using (
  class_id in (
    select id from classes where center_id in (
      select center_id from users where id = auth.uid() and role = 'admin'
    )
  )
);
