import 'server-only'
import {
  Document,
  Page,
  renderToBuffer,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer'

// The one fixed v1 report template (PRD: self-service template editor is out
// of scope — Gio edits this file directly as builder). Colors mirror the KOMS
// palette; @react-pdf needs concrete values, not CSS variables.

export interface ReportPdfInput {
  studentName: string
  className: string
  lessonsCompleted: number
  lessonsTotal: number
  attendanceSummary: string
  finalText: string
  generatedDate: string
}

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#ffffff',
    color: '#1a2733',
    fontFamily: 'Helvetica',
    fontSize: 11,
    paddingVertical: 48,
    paddingHorizontal: 56,
  },
  header: {
    borderBottomColor: '#0f766e',
    borderBottomWidth: 2,
    marginBottom: 24,
    paddingBottom: 12,
  },
  academy: {
    color: '#0f766e',
    fontFamily: 'Helvetica-Bold',
    fontSize: 18,
  },
  reportTitle: {
    color: '#64748b',
    fontSize: 10,
    letterSpacing: 2,
    marginTop: 4,
    textTransform: 'uppercase',
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  metaBlock: {
    flexGrow: 1,
  },
  metaLabel: {
    color: '#64748b',
    fontSize: 8,
    letterSpacing: 1,
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  metaValue: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 12,
  },
  progressStrip: {
    backgroundColor: '#f0fdfa',
    borderColor: '#0f766e',
    borderRadius: 4,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  progressText: {
    color: '#0f766e',
    fontFamily: 'Helvetica-Bold',
    fontSize: 11,
  },
  body: {
    lineHeight: 1.6,
  },
  paragraph: {
    marginBottom: 10,
  },
  footer: {
    borderTopColor: '#e2e8f0',
    borderTopWidth: 1,
    bottom: 32,
    color: '#94a3b8',
    fontSize: 8,
    left: 56,
    paddingTop: 8,
    position: 'absolute',
    right: 56,
  },
})

function ReportDocument({ input }: { input: ReportPdfInput }) {
  const paragraphs = input.finalText
    .split(/\n{2,}|\n/)
    .map((p) => p.trim())
    .filter(Boolean)

  return (
    <Document title={`${input.studentName} — Progress Report`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.academy}>Kodecoon Academy</Text>
          <Text style={styles.reportTitle}>Student Progress Report</Text>
        </View>

        <View style={styles.metaRow}>
          <View style={styles.metaBlock}>
            <Text style={styles.metaLabel}>Student</Text>
            <Text style={styles.metaValue}>{input.studentName}</Text>
          </View>
          <View style={styles.metaBlock}>
            <Text style={styles.metaLabel}>Program</Text>
            <Text style={styles.metaValue}>{input.className}</Text>
          </View>
          <View style={styles.metaBlock}>
            <Text style={styles.metaLabel}>Date</Text>
            <Text style={styles.metaValue}>{input.generatedDate}</Text>
          </View>
        </View>

        <View style={styles.progressStrip}>
          <Text style={styles.progressText}>
            {input.lessonsCompleted} / {input.lessonsTotal} lessons completed
          </Text>
          <Text style={styles.progressText}>{input.attendanceSummary}</Text>
        </View>

        <View style={styles.body}>
          {paragraphs.map((paragraph, index) => (
            <Text key={index} style={styles.paragraph}>
              {paragraph}
            </Text>
          ))}
        </View>

        <Text style={styles.footer} fixed>
          Generated by KOMS — Kodecoon Operations Management System
        </Text>
      </Page>
    </Document>
  )
}

export async function renderReportPdf(input: ReportPdfInput): Promise<Buffer> {
  return renderToBuffer(<ReportDocument input={input} />)
}
